### ISSUE TITLE
Project closure checklist

### ISSUE THREAD

**Issue by nehill197** [poissonconsulting/fish-passage-22b#2]
- [x] 1: Project completed by Analyst
- [ ] 2: Report is reviewed by the Line Manager for Technical correctness ❌
- [x] 3: Report is reviewed by a Senior Reviewer
- [x] 4: Report is reviewed by Project Manager
- [x] 5: Report is provided to the Client
- [ ] 6: Other deliverables are provided to the client (e.g Excel Spreadsheet of database) ❌
- [x] 7: Analytic report pushed to company website
- [ ] 8: Interpretive report uploaded to Zotero ❌
- [x] 9: Database archived
- [x] 10: GitHub Issues cleaned up

For details on each task refer to the [Project Management Book](https://poisson-project-management.netlify.app/checklists.html#analysis-closure-checklist)
